#ifndef CONFIG_SPWRTR_ENABLE
#define CONFIG_SPWRTR_ENABLE 0
#endif

#if defined CONFIG_SPWRTR_RX_SDR
#define CONFIG_SPWRTR_INPUT 2
#elif defined CONFIG_SPWRTR_RX_DDR
#define CONFIG_SPWRTR_INPUT 3
#elif defined CONFIG_SPWRTR_RX_XOR
#define CONFIG_SPWRTR_INPUT 0
#elif defined CONFIG_SPWRTR_RX_AFLEX
#define CONFIG_SPWRTR_INPUT 1
#else
#define CONFIG_SPWRTR_INPUT 2
#endif

#if defined CONFIG_SPWRTR_TX_SDR
#define CONFIG_SPWRTR_OUTPUT 0
#elif defined CONFIG_SPWRTR_TX_DDR
#define CONFIG_SPWRTR_OUTPUT 1
#elif defined CONFIG_SPWRTR_TX_AFLEX
#define CONFIG_SPWRTR_OUTPUT 2
#else
#define CONFIG_SPWRTR_OUTPUT 0
#endif

#ifndef CONFIG_SPWRTR_RTSAME
#define CONFIG_SPWRTR_RTSAME 0
#endif

#if defined CONFIG_SPWRTR_RXFIFO16
#define CONFIG_SPWRTR_RXFIFO 16
#elif defined CONFIG_SPWRTR_RXFIFO32
#define CONFIG_SPWRTR_RXFIFO 32
#elif defined CONFIG_SPWRTR_RXFIFO64
#define CONFIG_SPWRTR_RXFIFO 64
#elif defined CONFIG_SPWRTR_RXFIFO128
#define CONFIG_SPWRTR_RXFIFO 128
#elif defined CONFIG_SPWRTR_RXFIFO256
#define CONFIG_SPWRTR_RXFIFO 256
#elif defined CONFIG_SPWRTR_RXFIFO512
#define CONFIG_SPWRTR_RXFIFO 512
#elif defined CONFIG_SPWRTR_RXFIFO1024
#define CONFIG_SPWRTR_RXFIFO 1024
#elif defined CONFIG_SPWRTR_RXFIFO2048
#define CONFIG_SPWRTR_RXFIFO 2048
#else
#define CONFIG_SPWRTR_RXFIFO 64
#endif

#ifndef CONFIG_SPWRTR_TECHFIFO
#define CONFIG_SPWRTR_TECHFIFO 1
#endif


#if defined CONFIG_SPWRTR_FT_NOFT
#define CONFIG_SPWRTR_FT 0
#elif defined CONFIG_SPWRTR_FT_PAR
#define CONFIG_SPWRTR_FT 1
#elif defined CONFIG_SPWRTR_FT_TMR
#define CONFIG_SPWRTR_FT 2
#else
#define CONFIG_SPWRTR_FT 0
#endif

#ifndef CONFIG_SPWRTR_SPWEN
#define CONFIG_SPWRTR_SPWEN 0
#endif

#ifndef CONFIG_SPWRTR_AMBAEN
#define CONFIG_SPWRTR_AMBAEN 0
#endif

#ifndef CONFIG_SPWRTR_FIFOEN
#define CONFIG_SPWRTR_FIFOEN 0
#endif

#ifndef CONFIG_SPWRTR_SPWPORTS
#define CONFIG_SPWRTR_SPWPORTS 2
#endif

#ifndef CONFIG_SPWRTR_AMBAPORTS
#define CONFIG_SPWRTR_AMBAPORTS 0
#endif

#ifndef CONFIG_SPWRTR_FIFOPORTS
#define CONFIG_SPWRTR_FIFOPORTS 0
#endif

#if defined CONFIG_SPWRTR_ARB_RR
#define CONFIG_SPWRTR_ARB 0
#else
#define CONFIG_SPWRTR_ARB 0
#endif

#ifndef CONFIG_SPWRTR_RMAP
#define CONFIG_SPWRTR_RMAP 0
#endif

#ifndef CONFIG_SPWRTR_RMAPCRC
#define CONFIG_SPWRTR_RMAPCRC 0
#endif

#if defined CONFIG_SPWRTR_FIFO2_4
#define CONFIG_SPWRTR_FIFO2 4
#elif defined CONFIG_SPWRTR_FIFO2_8
#define CONFIG_SPWRTR_FIFO2 8
#elif defined CONFIG_SPWRTR_FIFO2_16
#define CONFIG_SPWRTR_FIFO2 16
#elif defined CONFIG_SPWRTR_FIFO2_32
#define CONFIG_SPWRTR_FIFO2 32
#else
#define CONFIG_SPWRTR_FIFO2 4
#endif

#ifndef CONFIG_SPWRTR_ALMOST
#define CONFIG_SPWRTR_ALMOST 8
#endif

#ifndef CONFIG_SPWRTR_RXUNAL
#define CONFIG_SPWRTR_RXUNAL 0
#endif

#if defined CONFIG_SPWRTR_RMAPBUF2
#define CONFIG_SPWRTR_RMAPBUF 2
#elif defined CONFIG_SPWRTR_RMAPBUF4
#define CONFIG_SPWRTR_RMAPBUF 4
#elif defined CONFIG_SPWRTR_RMAPBUF6
#define CONFIG_SPWRTR_RMAPBUF 6
#elif defined CONFIG_SPWRTR_RMAPBUF8
#define CONFIG_SPWRTR_RMAPBUF 8
#else
#define CONFIG_SPWRTR_RMAPBUF 4
#endif

#ifndef CONFIG_SPWRTR_DMACHAN
#define CONFIG_SPWRTR_DMACHAN 1
#endif

#ifndef CONFIG_SPWRTR_AHBSLVEN
#define CONFIG_SPWRTR_AHBSLVEN 1
#endif

#ifndef CONFIG_SPWRTR_TIMERBITS
#define CONFIG_SPWRTR_TIMERBITS 0
#endif

#ifndef CONFIG_SPWRTR_PNP
#define CONFIG_SPWRTR_PNP 1
#endif

#ifndef CONFIG_SPWRTR_AUTOSCRUB
#define CONFIG_SPWRTR_AUTOSCRUB 1
#endif


