set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]
  
set_property IOSTANDARD LVCMOS18 [get_ports switch]
set_property PACKAGE_PIN F22 [get_ports {switch[0]}]
set_property PACKAGE_PIN G22 [get_ports {switch[1]}]
set_property PACKAGE_PIN H22 [get_ports {switch[2]}]
set_property PACKAGE_PIN F21 [get_ports {switch[3]}]
set_property PACKAGE_PIN H19 [get_ports {switch[4]}]
set_property PACKAGE_PIN H18 [get_ports {switch[5]}]
set_property PACKAGE_PIN H17 [get_ports {switch[6]}]
set_property PACKAGE_PIN M15 [get_ports {switch[7]}]
  
set_property IOSTANDARD LVCMOS18 [get_ports button]
set_property PACKAGE_PIN R16 [get_ports {button[0]}] 
set_property PACKAGE_PIN N15 [get_ports {button[1]}]
set_property PACKAGE_PIN R18 [get_ports {button[2]}] 
set_property PACKAGE_PIN T18 [get_ports {button[3]}] 
  
set_false_path -from  [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
set_false_path -from  [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]

