onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/cpu/fabtech
add wave -noupdate /testbench/cpu/memtech
add wave -noupdate /testbench/cpu/padtech
add wave -noupdate /testbench/cpu/clktech
add wave -noupdate /testbench/cpu/disas
add wave -noupdate /testbench/cpu/dbguart
add wave -noupdate /testbench/cpu/pclow
add wave -noupdate /testbench/cpu/resetn
add wave -noupdate /testbench/cpu/clk
add wave -noupdate /testbench/cpu/clk2
add wave -noupdate /testbench/cpu/clk125
add wave -noupdate /testbench/cpu/wdogn
add wave -noupdate /testbench/cpu/address
add wave -noupdate /testbench/cpu/data
add wave -noupdate /testbench/cpu/oen
add wave -noupdate /testbench/cpu/writen
add wave -noupdate /testbench/cpu/romsn
add wave -noupdate /testbench/cpu/ddr_clk
add wave -noupdate /testbench/cpu/ddr_clkb
add wave -noupdate /testbench/cpu/ddr_cke
add wave -noupdate /testbench/cpu/ddr_odt
add wave -noupdate /testbench/cpu/ddr_we
add wave -noupdate /testbench/cpu/ddr_ras
add wave -noupdate /testbench/cpu/ddr_csn
add wave -noupdate /testbench/cpu/ddr_cas
add wave -noupdate /testbench/cpu/ddr_dm
add wave -noupdate /testbench/cpu/ddr_dqs
add wave -noupdate /testbench/cpu/ddr_dqsn
add wave -noupdate /testbench/cpu/ddr_ad
add wave -noupdate /testbench/cpu/ddr_ba
add wave -noupdate /testbench/cpu/ddr_dq
add wave -noupdate /testbench/cpu/ddr_rzq
add wave -noupdate /testbench/cpu/ddr_zio
add wave -noupdate /testbench/cpu/txd1
add wave -noupdate /testbench/cpu/rxd1
add wave -noupdate /testbench/cpu/ctsn1
add wave -noupdate /testbench/cpu/rtsn1
add wave -noupdate /testbench/cpu/txd2
add wave -noupdate /testbench/cpu/rxd2
add wave -noupdate /testbench/cpu/ctsn2
add wave -noupdate /testbench/cpu/rtsn2
add wave -noupdate /testbench/cpu/pio
add wave -noupdate /testbench/cpu/genio
add wave -noupdate /testbench/cpu/switch
add wave -noupdate /testbench/cpu/led
add wave -noupdate /testbench/cpu/erx_clk
add wave -noupdate /testbench/cpu/emdio
add wave -noupdate /testbench/cpu/erxd
add wave -noupdate /testbench/cpu/erx_dv
add wave -noupdate /testbench/cpu/emdint
add wave -noupdate /testbench/cpu/etx_clk
add wave -noupdate /testbench/cpu/etxd
add wave -noupdate /testbench/cpu/etx_en
add wave -noupdate /testbench/cpu/emdc
add wave -noupdate /testbench/cpu/ps2clk
add wave -noupdate /testbench/cpu/ps2data
add wave -noupdate /testbench/cpu/iic_scl
add wave -noupdate /testbench/cpu/iic_sda
add wave -noupdate /testbench/cpu/ddc_scl
add wave -noupdate /testbench/cpu/ddc_sda
add wave -noupdate /testbench/cpu/dvi_iic_scl
add wave -noupdate /testbench/cpu/dvi_iic_sda
add wave -noupdate /testbench/cpu/tft_lcd_data
add wave -noupdate /testbench/cpu/tft_lcd_clk_p
add wave -noupdate /testbench/cpu/tft_lcd_clk_n
add wave -noupdate /testbench/cpu/tft_lcd_hsync
add wave -noupdate /testbench/cpu/tft_lcd_vsync
add wave -noupdate /testbench/cpu/tft_lcd_de
add wave -noupdate /testbench/cpu/tft_lcd_reset_b
add wave -noupdate /testbench/cpu/spw_clk
add wave -noupdate /testbench/cpu/spw_rxdp
add wave -noupdate /testbench/cpu/spw_rxdn
add wave -noupdate /testbench/cpu/spw_rxsp
add wave -noupdate /testbench/cpu/spw_rxsn
add wave -noupdate /testbench/cpu/spw_txdp
add wave -noupdate /testbench/cpu/spw_txdn
add wave -noupdate /testbench/cpu/spw_txsp
add wave -noupdate /testbench/cpu/spw_txsn
add wave -noupdate /testbench/cpu/spi_sel_n
add wave -noupdate /testbench/cpu/spi_clk
add wave -noupdate /testbench/cpu/spi_mosi
add wave -noupdate /testbench/cpu/vcc
add wave -noupdate /testbench/cpu/gnd
add wave -noupdate /testbench/cpu/memi
add wave -noupdate /testbench/cpu/memo
add wave -noupdate /testbench/cpu/wpo
add wave -noupdate /testbench/cpu/sdi
add wave -noupdate /testbench/cpu/sdo
add wave -noupdate /testbench/cpu/leds
add wave -noupdate /testbench/cpu/apbi
add wave -noupdate /testbench/cpu/apbi2
add wave -noupdate /testbench/cpu/apbo
add wave -noupdate /testbench/cpu/apbo2
add wave -noupdate /testbench/cpu/ahbsi
add wave -noupdate /testbench/cpu/ahbso
add wave -noupdate /testbench/cpu/ahbmi
add wave -noupdate /testbench/cpu/vahbmi
add wave -noupdate /testbench/cpu/ahbmo
add wave -noupdate /testbench/cpu/vahbmo
add wave -noupdate /testbench/cpu/clkm
add wave -noupdate /testbench/cpu/rstn
add wave -noupdate /testbench/cpu/rstraw
add wave -noupdate /testbench/cpu/sdclkl
add wave -noupdate /testbench/cpu/clk_200
add wave -noupdate /testbench/cpu/clk25
add wave -noupdate /testbench/cpu/clk40
add wave -noupdate /testbench/cpu/clk65
add wave -noupdate /testbench/cpu/cgi
add wave -noupdate /testbench/cpu/cgi2
add wave -noupdate /testbench/cpu/cgi3
add wave -noupdate /testbench/cpu/cgo
add wave -noupdate /testbench/cpu/cgo2
add wave -noupdate /testbench/cpu/cgo3
add wave -noupdate /testbench/cpu/u1i
add wave -noupdate /testbench/cpu/u2i
add wave -noupdate /testbench/cpu/dui
add wave -noupdate /testbench/cpu/u1o
add wave -noupdate /testbench/cpu/u2o
add wave -noupdate /testbench/cpu/duo
add wave -noupdate /testbench/cpu/irqi
add wave -noupdate /testbench/cpu/irqo
add wave -noupdate /testbench/cpu/dbgi
add wave -noupdate /testbench/cpu/dbgo
add wave -noupdate /testbench/cpu/dsui
add wave -noupdate /testbench/cpu/dsuo
add wave -noupdate /testbench/cpu/gmiii
add wave -noupdate /testbench/cpu/rgmiii
add wave -noupdate /testbench/cpu/rgmiii_buf
add wave -noupdate /testbench/cpu/rgmii_pad
add wave -noupdate /testbench/cpu/gmiio
add wave -noupdate /testbench/cpu/rgmiio
add wave -noupdate /testbench/cpu/gpti
add wave -noupdate /testbench/cpu/gpto
add wave -noupdate /testbench/cpu/gpioi
add wave -noupdate /testbench/cpu/gpioo
add wave -noupdate /testbench/cpu/gpioi2
add wave -noupdate /testbench/cpu/gpioo2
add wave -noupdate /testbench/cpu/gpioi3
add wave -noupdate /testbench/cpu/gpioo3
add wave -noupdate /testbench/cpu/can_lrx
add wave -noupdate /testbench/cpu/can_ltx
add wave -noupdate /testbench/cpu/lock
add wave -noupdate /testbench/cpu/calib_done
add wave -noupdate /testbench/cpu/clkml
add wave -noupdate /testbench/cpu/lclk
add wave -noupdate /testbench/cpu/rst
add wave -noupdate /testbench/cpu/ndsuact
add wave -noupdate /testbench/cpu/wdogl
add wave -noupdate /testbench/cpu/tck
add wave -noupdate /testbench/cpu/tckn
add wave -noupdate /testbench/cpu/tms
add wave -noupdate /testbench/cpu/tdi
add wave -noupdate /testbench/cpu/tdo
add wave -noupdate /testbench/cpu/ethclk
add wave -noupdate /testbench/cpu/ddr2clk
add wave -noupdate /testbench/cpu/kbdi
add wave -noupdate /testbench/cpu/kbdo
add wave -noupdate /testbench/cpu/moui
add wave -noupdate /testbench/cpu/mouo
add wave -noupdate /testbench/cpu/vgao
add wave -noupdate /testbench/cpu/lcd_datal
add wave -noupdate /testbench/cpu/lcd_hsyncl
add wave -noupdate /testbench/cpu/lcd_vsyncl
add wave -noupdate /testbench/cpu/lcd_del
add wave -noupdate /testbench/cpu/lcd_reset_bl
add wave -noupdate /testbench/cpu/i2ci
add wave -noupdate /testbench/cpu/dvi_i2ci
add wave -noupdate /testbench/cpu/i2co
add wave -noupdate /testbench/cpu/dvi_i2co
add wave -noupdate /testbench/cpu/spmi
add wave -noupdate /testbench/cpu/spmo
add wave -noupdate /testbench/cpu/spmi2
add wave -noupdate /testbench/cpu/spmo2
add wave -noupdate /testbench/cpu/spwi
add wave -noupdate /testbench/cpu/spwo
add wave -noupdate /testbench/cpu/dtmp
add wave -noupdate /testbench/cpu/stmp
add wave -noupdate /testbench/cpu/spw_rxtxclk
add wave -noupdate /testbench/cpu/spw_rxclkn
add wave -noupdate /testbench/cpu/spw_rxclk
add wave -noupdate /testbench/cpu/spw_rstn
add wave -noupdate /testbench/cpu/spw_rstn_sync
add wave -noupdate /testbench/cpu/stati
add wave -noupdate /testbench/cpu/fpi
add wave -noupdate /testbench/cpu/fpo
add wave -noupdate /testbench/cpu/rstgtxn
add wave -noupdate /testbench/cpu/idelay_reset_cnt
add wave -noupdate /testbench/cpu/idelay_cal_cnt
add wave -noupdate /testbench/cpu/idelayctrl_reset
add wave -noupdate /testbench/cpu/idelayctrl_cal
add wave -noupdate /testbench/cpu/rgmiii_rx_clk_n
add wave -noupdate /testbench/cpu/rgmiii_rx_clk_n_buf
add wave -noupdate /testbench/cpu/rgmiio_tx_clk
add wave -noupdate /testbench/cpu/rgmiio_tx_en
add wave -noupdate /testbench/cpu/rgmiio_txd
add wave -noupdate /testbench/cpu/core_ddr_clk
add wave -noupdate /testbench/cpu/core_ddr_clkb
add wave -noupdate /testbench/cpu/core_ddr_cke
add wave -noupdate /testbench/cpu/core_ddr_csb
add wave -noupdate /testbench/cpu/core_ddr_ad
add wave -noupdate /testbench/cpu/core_ddr_odt
add wave -noupdate /testbench/cpu/video_clk
add wave -noupdate /testbench/cpu/clk50
add wave -noupdate /testbench/cpu/clk100
add wave -noupdate /testbench/cpu/spw100
add wave -noupdate /testbench/cpu/clk_sel
add wave -noupdate /testbench/cpu/clkvga
add wave -noupdate /testbench/cpu/clkvga_p
add wave -noupdate /testbench/cpu/clkvga_n
add wave -noupdate /testbench/cpu/clk_125
add wave -noupdate /testbench/cpu/clk_125_pll
add wave -noupdate /testbench/cpu/clk_125_bufg
add wave -noupdate /testbench/cpu/nerror
add wave -noupdate /testbench/cpu/use_eth_input_delay
add wave -noupdate /testbench/cpu/use_eth_output_delay
add wave -noupdate /testbench/cpu/use_eth_data_output_delay
add wave -noupdate /testbench/cpu/use_eth_input_delay_clk
add wave -noupdate /testbench/cpu/use_gtx_clk
add wave -noupdate /testbench/cpu/blength
add wave -noupdate /testbench/cpu/fifodepth
add wave -noupdate /testbench/cpu/maxahbm
add wave -noupdate /testbench/cpu/BOARD_FREQ
add wave -noupdate /testbench/cpu/CPU_FREQ
add wave -noupdate /testbench/cpu/IOAEN
add wave -noupdate /testbench/cpu/DDR2_FREQ
add wave -noupdate /testbench/cpu/SPW_LOOP_BACK
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
configure wave -namecolwidth 241
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {943653 ps}
