onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/clk
add wave -noupdate /testbench/rst
add wave -noupdate /testbench/GND
add wave -noupdate /testbench/VCC
add wave -noupdate /testbench/NC
add wave -noupdate /testbench/ddr_clk
add wave -noupdate /testbench/ddr_clkb
add wave -noupdate /testbench/ddr_cke
add wave -noupdate /testbench/ddr_we
add wave -noupdate /testbench/ddr_ras
add wave -noupdate /testbench/ddr_cas
add wave -noupdate /testbench/ddr_dm
add wave -noupdate /testbench/ddr_dqs
add wave -noupdate /testbench/ddr_dqsn
add wave -noupdate /testbench/ddr_ad
add wave -noupdate /testbench/ddr_ba
add wave -noupdate /testbench/ddr_dq
add wave -noupdate /testbench/ddr_odt
add wave -noupdate /testbench/ddr_rzq
add wave -noupdate /testbench/ddr_zio
add wave -noupdate /testbench/ddr_csb
add wave -noupdate /testbench/txd1
add wave -noupdate /testbench/rxd1
add wave -noupdate /testbench/genio
add wave -noupdate /testbench/switch
add wave -noupdate /testbench/led
add wave -noupdate /testbench/button
add wave -noupdate /testbench/erx_clk
add wave -noupdate /testbench/erxd
add wave -noupdate /testbench/erx_dv
add wave -noupdate /testbench/erx_er
add wave -noupdate /testbench/erx_col
add wave -noupdate /testbench/erx_crs
add wave -noupdate /testbench/etx_clk
add wave -noupdate /testbench/etxd
add wave -noupdate /testbench/etx_en
add wave -noupdate /testbench/etx_er
add wave -noupdate /testbench/egtxclk
add wave -noupdate /testbench/emdc
add wave -noupdate /testbench/emdio
add wave -noupdate /testbench/emdint
add wave -noupdate /testbench/ps2clk
add wave -noupdate /testbench/ps2data
add wave -noupdate /testbench/spi_sel_n
add wave -noupdate /testbench/spi_clk
add wave -noupdate /testbench/spi_mosi
add wave -noupdate /testbench/spi_miso
add wave -noupdate /testbench/errorn
add wave -noupdate /testbench/cpu/resetn
add wave -noupdate /testbench/cpu/clk
add wave -noupdate /testbench/cpu/ddr_clk
add wave -noupdate /testbench/cpu/ddr_clkb
add wave -noupdate /testbench/cpu/ddr_cke
add wave -noupdate /testbench/cpu/ddr_odt
add wave -noupdate /testbench/cpu/ddr_we
add wave -noupdate /testbench/cpu/ddr_ras
add wave -noupdate /testbench/cpu/ddr_cas
add wave -noupdate /testbench/cpu/ddr_dm
add wave -noupdate /testbench/cpu/ddr_dqs
add wave -noupdate /testbench/cpu/ddr_dqsn
add wave -noupdate /testbench/cpu/ddr_ad
add wave -noupdate /testbench/cpu/ddr_ba
add wave -noupdate /testbench/cpu/ddr_dq
add wave -noupdate /testbench/cpu/ddr_rzq
add wave -noupdate /testbench/cpu/ddr_zio
add wave -noupdate /testbench/cpu/txd1
add wave -noupdate /testbench/cpu/rxd1
add wave -noupdate /testbench/cpu/pmoda
add wave -noupdate /testbench/cpu/switch
add wave -noupdate /testbench/cpu/led
add wave -noupdate /testbench/cpu/button
add wave -noupdate /testbench/cpu/erx_clk
add wave -noupdate /testbench/cpu/erxd
add wave -noupdate /testbench/cpu/erx_dv
add wave -noupdate /testbench/cpu/erx_er
add wave -noupdate /testbench/cpu/erx_col
add wave -noupdate /testbench/cpu/erx_crs
add wave -noupdate /testbench/cpu/etx_clk
add wave -noupdate /testbench/cpu/etxd
add wave -noupdate /testbench/cpu/etx_en
add wave -noupdate /testbench/cpu/etx_er
add wave -noupdate /testbench/cpu/erst
add wave -noupdate /testbench/cpu/egtxclk
add wave -noupdate /testbench/cpu/emdc
add wave -noupdate /testbench/cpu/emdio
add wave -noupdate /testbench/cpu/emdint
add wave -noupdate /testbench/cpu/kbd_clk
add wave -noupdate /testbench/cpu/kbd_data
add wave -noupdate /testbench/cpu/mou_clk
add wave -noupdate /testbench/cpu/mou_data
add wave -noupdate /testbench/cpu/spi_sel_n
add wave -noupdate /testbench/cpu/spi_clk
add wave -noupdate /testbench/cpu/spi_miso
add wave -noupdate /testbench/cpu/spi_mosi
add wave -noupdate /testbench/cpu/tmdstx_clk_p
add wave -noupdate /testbench/cpu/tmdstx_clk_n
add wave -noupdate /testbench/cpu/tmdstx_dat_p
add wave -noupdate /testbench/cpu/tmdstx_dat_n
add wave -noupdate /testbench/cpu/vcc
add wave -noupdate /testbench/cpu/gnd
add wave -noupdate /testbench/cpu/memi
add wave -noupdate /testbench/cpu/memo
add wave -noupdate /testbench/cpu/wpo
add wave -noupdate /testbench/cpu/sdo
add wave -noupdate /testbench/cpu/apbi
add wave -noupdate /testbench/cpu/apbo
add wave -noupdate /testbench/cpu/ahbsi
add wave -noupdate /testbench/cpu/ahbso
add wave -noupdate /testbench/cpu/ahbmi
add wave -noupdate /testbench/cpu/ahbmo
add wave -noupdate /testbench/cpu/clkm
add wave -noupdate /testbench/cpu/rstn
add wave -noupdate /testbench/cpu/rstraw
add wave -noupdate /testbench/cpu/clk200
add wave -noupdate /testbench/cpu/cgi
add wave -noupdate /testbench/cpu/cgo
add wave -noupdate /testbench/cpu/u1i
add wave -noupdate /testbench/cpu/dui
add wave -noupdate /testbench/cpu/u1o
add wave -noupdate /testbench/cpu/duo
add wave -noupdate /testbench/cpu/irqi
add wave -noupdate /testbench/cpu/irqo
add wave -noupdate /testbench/cpu/dbgi
add wave -noupdate /testbench/cpu/dbgo
add wave -noupdate /testbench/cpu/dsui
add wave -noupdate /testbench/cpu/dsuo
add wave -noupdate /testbench/cpu/ethi
add wave -noupdate /testbench/cpu/etho
add wave -noupdate /testbench/cpu/gpti
add wave -noupdate /testbench/cpu/gpto
add wave -noupdate /testbench/cpu/gpioi
add wave -noupdate /testbench/cpu/gpioo
add wave -noupdate /testbench/cpu/lock
add wave -noupdate /testbench/cpu/calib_done
add wave -noupdate /testbench/cpu/lclk
add wave -noupdate /testbench/cpu/rstext
add wave -noupdate /testbench/cpu/rstint
add wave -noupdate /testbench/cpu/errorp
add wave -noupdate /testbench/cpu/tck
add wave -noupdate /testbench/cpu/tckn
add wave -noupdate /testbench/cpu/tms
add wave -noupdate /testbench/cpu/tdi
add wave -noupdate /testbench/cpu/tdo
add wave -noupdate /testbench/cpu/ddr2clk
add wave -noupdate /testbench/cpu/ddr0_clk_fb
add wave -noupdate /testbench/cpu/ddr0_clk
add wave -noupdate /testbench/cpu/ddr0_clkb
add wave -noupdate /testbench/cpu/ddr0_cke
add wave -noupdate /testbench/cpu/ddr0_odt
add wave -noupdate /testbench/cpu/ddr0_ad
add wave -noupdate /testbench/cpu/ddr0_lock
add wave -noupdate /testbench/cpu/spmi
add wave -noupdate /testbench/cpu/spmo
add wave -noupdate /testbench/cpu/kbdi
add wave -noupdate /testbench/cpu/kbdo
add wave -noupdate /testbench/cpu/moui
add wave -noupdate /testbench/cpu/mouo
add wave -noupdate /testbench/cpu/vgao
add wave -noupdate /testbench/cpu/video_clk
add wave -noupdate /testbench/cpu/video_fastclk
add wave -noupdate /testbench/cpu/video_clksel
add wave -noupdate /testbench/cpu/tmds_clk
add wave -noupdate /testbench/cpu/tmds_dat
add wave -noupdate /testbench/cpu/stati
add wave -noupdate /testbench/cpu/fpi
add wave -noupdate /testbench/cpu/fpo
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6662738 ps} 0} {{Cursor 3} {341676502 ps} 0}
configure wave -namecolwidth 212
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {337706096 ps} {349485406 ps}
